/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-03-23 03:20:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.my.vo.Product;
import java.util.List;

public final class productlistresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/searchproduct.jsp", Long.valueOf(1616467976591L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.my.vo.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("    box-sizing: border-box; /* width값이 전체 너비 */\r\n");
      out.write("    padding : 0;\r\n");
      out.write("    margin : 0;\r\n");
      out.write("}\r\n");
      out.write("div.productlist{\r\n");
      out.write("\t/* position : relative; */\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 600px;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("div.productlist>div.product{\r\n");
      out.write("    width : 300px;\r\n");
      out.write("    height : 300px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border: 1px dotted;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    float: left;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("div.productlist>div.product>ul{\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("div.productlist>div.product>ul>li>img{\r\n");
      out.write("\twidth : 80%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!--jquery사용-->\r\n");
      out.write("<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script> \r\n");
      out.write(" -->\r\n");
      out.write(" <script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t//alert(\"productlist\");\r\n");
      out.write("\t//DOM트리에서 class속성값이 product인 div객체찾기\r\n");
      out.write("\tvar $productDivObj = $(\"div.productlist>div.product\");\r\n");
      out.write("\t\r\n");
      out.write("\t$productDivObj.each(function(index, element){\r\n");
      out.write("\t\t$(element).click(function(){\r\n");
      out.write("\t\t\tvar imgSrc = $(this).find(\"ul>li.prod_no>img\").attr(\"src\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar lastSlash = imgSrc.lastIndexOf(\"/\"); //마지막 슬래시 위치\r\n");
      out.write("\t\t\tvar ext = imgSrc.indexOf(\".jpg\"); //.jpg파일확장자 위치\r\n");
      out.write("\t\t\tvar prod_no = imgSrc.substring(lastSlash+1, ext);\r\n");
      out.write("\t\t\talert(\"상품이 클릭되었습니다. 상품번호:\" + prod_no);\r\n");
      out.write("\t\t\tvar prod_name = $(this).find(\"ul>li.prod_name\").html();\r\n");
      out.write("\t\t\tvar prod_price = $(this).find(\"ul>li.prod_price\").html();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"section>article\").empty();\r\n");
      out.write("\t\t\tvar url = \"./product/detail\";\r\n");
      out.write("\t\t\tvar method = \"get\";\r\n");
      out.write("\t\t\tvar data = \"prod_no=\" + prod_no;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : url,\t\r\n");
      out.write("\t\t\t\tmethod : method,\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t$(\"section>article\").html(data);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(jqXHR){\r\n");
      out.write("\t\t\t\t\talert(\"오류:\" + jqXHR.status);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script> \r\n");
      out.write("<div class=\"productlist\">    \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("div.searchproduct{\r\n");
      out.write("\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    margin : 10px;\r\n");
      out.write("    top: 9px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    vertical-align: baseline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.searchproduct>input[name=product]{\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: #777;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    height: 22px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    padding: 0 10px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 5px;\r\n");
      out.write("    width: 80%;\r\n");
      out.write("}\r\n");
      out.write("div.searchproduct>img{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    /* vertical-align: middle; */\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    top: 5px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script> \r\n");
      out.write(" -->\r\n");
      out.write(" <script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"div.searchproduct>img\").click(function(){\r\n");
      out.write("\t\t//var url = \"./searchproduct\";\r\n");
      out.write("\t\tvar url = \"./product/list\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar method = \"post\";\r\n");
      out.write("\t\tvar data = \"prod=\" + $(\"div.searchproduct>input[name=product]\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"section>article>div.productlist>div.product\").remove();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tmethod : method,\r\n");
      out.write("\t\t\tdata : data,\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\"section>article\").html(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR){\r\n");
      out.write("\t\t\t\talert(\"오류:\" + jqXHR.status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});//end of ajax\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"searchproduct\">\r\n");
      out.write("   <input type=\"text\" placeholder=\"통합검색\" name=\"product\" >\r\n");
      out.write("  <!--  <input type=\"button\" value=\"검색\"> -->\r\n");
      out.write("   <img alt=\"통합검색\" src=\"./images/icon_magnifier_black.png\">\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');

//3. 요청속성얻기
List<Product> list = (List)request.getAttribute("list");
for(Product p: list){

      out.write("\r\n");
      out.write(" <!--하나의 상품-->\r\n");
      out.write(" <div class=\"product\">\r\n");
      out.write("     <ul>\r\n");
      out.write("         <li class=\"prod_no\"><img src=\"./images/");
      out.print(p.getProd_no() );
      out.write(".jpg\" alt=\"");
      out.print(p.getProd_name() );
      out.write("\"></li>\r\n");
      out.write("         <li class=\"prod_name\">");
      out.print(p.getProd_name() );
      out.write("</li>\r\n");
      out.write("         <li class=\"prod_price\">");
      out.print(p.getProd_price() );
      out.write("</li>\r\n");
      out.write("     </ul>\r\n");
      out.write(" </div>\r\n");
}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
