/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-03-23 05:56:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class semanticcssjq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>시멘틱태그-CSS-jQuery[JSP]</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            * { \r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("\r\n");
      out.write("                color : #000000; \r\n");
      out.write("                /* font-size: 1.25em; */\r\n");
      out.write("            }\r\n");
      out.write("            header { background: #f6f5ef; \r\n");
      out.write("                     margin: 5px auto;\r\n");
      out.write("                     position: relative;\r\n");
      out.write("            } \r\n");
      out.write("            /*section{background-color:#eef2f3; height:500px; margin-bottom: 5px;}\r\n");
      out.write("            section>article.one{background-color: #b3ffd9}\r\n");
      out.write("            section>article.two{background-color: #1e3932;color:white;}*/\r\n");
      out.write("            footer{ background-color: #2C2A29;  color:#fff;  }\r\n");
      out.write("            header, footer { height:100px; /* width: 1100px; */ width:100%; }\r\n");
      out.write("            header>nav>ul{ list-style-type: none; padding: 0px;}\r\n");
      out.write("            header>nav>ul>li{ \r\n");
      out.write("             width:100px; \r\n");
      out.write("             display: inline-block; \r\n");
      out.write("             margin: 0px 10px; \r\n");
      out.write("             text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            header>nav>ul>li>a{\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("            }\r\n");
      out.write("            header>nav>ul>li>a:hover{\r\n");
      out.write("                background-color: black;\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            header>h1{\r\n");
      out.write("                width: 30%;    \r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                border: 1px solid;\r\n");
      out.write("            }\r\n");
      out.write("            /* 이미지 로고 */\r\n");
      out.write("            header>h1>a{\r\n");
      out.write("                display: block;\r\n");
      out.write("                width : 100%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                \r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 10px;\r\n");
      out.write("                left: 0px;\r\n");
      out.write("                \r\n");
      out.write("                background-image: url('./images/logo.png');\r\n");
      out.write("                background-repeat: no-repeat;\r\n");
      out.write("            }\r\n");
      out.write("            header>nav{\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                width : 60%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                border: 1px solid;\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 0px;\r\n");
      out.write("                right: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            section{\r\n");
      out.write("                background-color:#eef2f3; \r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height:500px; \r\n");
      out.write("                margin : 5px;\r\n");
      out.write("            }\r\n");
      out.write("            section>article{\r\n");
      out.write("                width: 80%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("            section>aside{\r\n");
      out.write("                width: 20%;\r\n");
      out.write("                height:100%;\r\n");
      out.write("                float: right;               \r\n");
      out.write("            }\r\n");
      out.write("            section>aside>div.strawberry, section>aside>div.plcc{\r\n");
      out.write("            \twidth: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            /* 광고이미지 반응*/\r\n");
      out.write("            section>aside .pc-badge{\r\n");
      out.write("            \twidth: 80%;\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("            section>aside .mobile-badge {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            @media screen and (max-width: 960px){\r\n");
      out.write("                section>aside .pc-badge {\r\n");
      out.write("                    display: none;\r\n");
      out.write("                }\r\n");
      out.write("               section>aside .mobile-badge {\r\n");
      out.write("               \t\twidth: 80%;\r\n");
      out.write("                   display: block;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /*메뉴 반응*/\r\n");
      out.write("            header>nav.small{\r\n");
      out.write("                display:none;\r\n");
      out.write("            }\r\n");
      out.write("            @media screen and (min-width: 641px) and (max-width: 960px){\r\n");
      out.write("                header>nav.small{\r\n");
      out.write("                    display:inline-block;\r\n");
      out.write("                }\r\n");
      out.write("                header>nav.large{\r\n");
      out.write("                    display:none;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <style>\r\n");
      out.write("        div.viewcart{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        div.viewcart>table{\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("        div.viewcart>table tr{\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        div.viewcart>table, div.viewcart>table th, div.viewcart>table td{\r\n");
      out.write("            border: 1px solid;\r\n");
      out.write("        }   \r\n");
      out.write("        </style>\r\n");
      out.write("        <style>\r\n");
      out.write("          div.vieworder{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("        }\r\n");
      out.write("        div.vieworder>table{\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("        div.vieworder>table tr{\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        div.vieworder>table, div.vieworder>table th, div.vieworder>table td{\r\n");
      out.write("            border: 1px solid;\r\n");
      out.write("        }   \r\n");
      out.write("        </style>\r\n");
      out.write("<!--jquery사용-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script> \r\n");
      out.write("<script>\r\n");
      out.write("let backContextPath = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("$(function(){            \t\r\n");
      out.write("//DOM트리에서 메뉴객체들 모두찾기\r\n");
      out.write("var $menuObj = $(\"header>nav>ul>li>a\");\r\n");
      out.write("//메뉴가 클릭되면 \r\n");
      out.write("$menuObj.click(function(event){\r\n");
      out.write("    $(\"section>article\").empty(); //aricle영역 지우기\r\n");
      out.write("    //메뉴객체의 href속성값 얻기\r\n");
      out.write("    var hrefValue = $(event.target).attr(\"href\");//ex)login.html, signup.html\r\n");
      out.write("\r\n");
      out.write("    alert(\"메뉴:\" + hrefValue+\"를 선택했습니다.\");\r\n");
      out.write("    switch(hrefValue){//메뉴별\r\n");
      out.write("        case 'logout': //로그아웃메뉴\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:hrefValue,\r\n");
      out.write("            method: 'get',\r\n");
      out.write("            success: function(data){//성공응답\r\n");
      out.write("                location.href=backContextPath+\"/semanticcssjq\";\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR){//실패응답\r\n");
      out.write("                    alert(\"AJAX요청응답 실패 : 에러코드=\" + jqXHR.status);\r\n");
      out.write("                } \r\n");
      out.write("        });\r\n");
      out.write("        break;\r\n");
      out.write("        case 'viewcart': //장바구니보기메뉴\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: hrefValue,\r\n");
      out.write("            method: 'get',\r\n");
      out.write("            success:function(responseObj){\r\n");
      out.write("                if(responseObj.status == undefined){ //장바구니가 있는경우\r\n");
      out.write("                    var $tableObj = $(\"<table>\");//객체생성  //$(\"table\") <-선택자이용해서 객체를 DOM에서 찾기\r\n");
      out.write("                    var tableData = \"<tr><th>상품번호</th><th>상품명</th><th>가격</th><th>수량</th></tr>\";\r\n");
      out.write("                    var arr = responseObj;\r\n");
      out.write("                    $(arr).each(function(index, element){\r\n");
      out.write("    //console.log(\"장바구니 내용 상품번호-\" + element.prod_no + \", 상품명-\" + element.prod_name+ \", 상품가격-\" + element.prod_price + \", 수량-\" + element.quantity);\r\n");
      out.write("                        tableData += '<tr>';\r\n");
      out.write("                        tableData += '<td>';\r\n");
      out.write("                        tableData += element.prod_no;\r\n");
      out.write("                        tableData += '</td>';\r\n");
      out.write("                        \r\n");
      out.write("                        tableData += '<td>';\r\n");
      out.write("                        tableData += element.prod_name;\r\n");
      out.write("                        tableData += '</td>';\r\n");
      out.write("                        \r\n");
      out.write("                        tableData += '<td>';\r\n");
      out.write("                        tableData += element.prod_price;\r\n");
      out.write("                        tableData += '</td>';\r\n");
      out.write("                        \r\n");
      out.write("                        tableData += '<td>';\r\n");
      out.write("                        tableData += element.quantity;\r\n");
      out.write("                        tableData += '</td>';\r\n");
      out.write("                        tableData += '</tr>';\r\n");
      out.write("                    });\r\n");
      out.write("                    $tableObj.html(tableData);\r\n");
      out.write("                    var $viewcartObj = $(\"<div class=viewcart>\");\r\n");
      out.write("                    var $h1Obj = $(\"<h1>장바구니</h1>\");\r\n");
      out.write("                    $viewcartObj.append($h1Obj);\r\n");
      out.write("                    $viewcartObj.append($tableObj);\r\n");
      out.write("                    var $btObj = $('<button>주문하기</button>'); //'<input type=\"button\" value=\"주문하기\">'\r\n");
      out.write("                    $viewcartObj.append($btObj);\r\n");
      out.write("                    $(\"section>article\").append($viewcartObj);\r\n");
      out.write("                    \r\n");
      out.write("                }else if(responseObj.status == -1){//장바구니가 없는경우\r\n");
      out.write("                    alert(\"장바구니가 비었습니다\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        break;\r\n");
      out.write("        case \"vieworder\":\r\n");
      out.write("      \t  $.ajax({\r\n");
      out.write("                url: hrefValue,\r\n");
      out.write("                method: 'get',\r\n");
      out.write("                success:function(responseObj){\r\n");
      out.write("                    if(responseObj.status == 1){ \r\n");
      out.write("                        var $tableObj = $('<table>');//객체생성  //$(\"table\") <-선택자이용해서 객체를 DOM에서 찾기\r\n");
      out.write("                        var tableData = \"<tr><th>주문번호</th><th>주문일자</th><th>상품번호</th><th>상품명</th>    <th>가격</th><th>주문수량</th></tr>\";\r\n");
      out.write("                        var arr = responseObj.list;\r\n");
      out.write("                        $(arr).each(function(index, info){\r\n");
      out.write("                        \tvar rowSize = info.lines.length;\r\n");
      out.write("                            tableData += '<tr>';\r\n");
      out.write("                            tableData += '<td rowspan=\"'+ rowSize + '\">';\r\n");
      out.write("                            tableData += info.order_no;\r\n");
      out.write("                            tableData += '</td>';\r\n");
      out.write("                            tableData += '<td rowspan=\"'+ rowSize + '\">';\r\n");
      out.write("                            tableData += info.order_dt;\r\n");
      out.write("                            tableData += '</td>';\r\n");
      out.write("                            $(info.lines).each(function(index, line){\r\n");
      out.write("                            \tif(index > 0){\r\n");
      out.write("                            \t\ttableData += '</tr>';\r\n");
      out.write("                            \t\ttableData += '<tr>';\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \ttableData += '<td>'+ line.p.prod_no+'</td>';\r\n");
      out.write("                            \ttableData += '<td>'+ line.p.prod_name+'</td>';\r\n");
      out.write("                            \ttableData += '<td>'+ line.p.prod_price+'</td>';\r\n");
      out.write("                            \ttableData += '<td>'+ line.order_quantity+'</td>';\r\n");
      out.write("                            });\r\n");
      out.write("                            tableData += '</tr>';\r\n");
      out.write("                        });\r\n");
      out.write("                        $tableObj.html(tableData);\r\n");
      out.write("                        var $vieworderObj = $('<div class=vieworder>');\r\n");
      out.write("                        var $h1Obj = $(\"<h1>주문내역</h1>\");\r\n");
      out.write("                        $vieworderObj.append($h1Obj);\r\n");
      out.write("                        $vieworderObj.append($tableObj);\r\n");
      out.write("                        $(\"section>article\").append($vieworderObj);\r\n");
      out.write("                        \r\n");
      out.write("                    }else if(responseObj.status == -1){\r\n");
      out.write("                        alert(\"주문내역이없습니다\");\r\n");
      out.write("                    }else if(responseObj.status == 0){\r\n");
      out.write("                    \talert(\"로그인부터 하세요\");\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        \tbreak;\r\n");
      out.write("        default: //그외의 메뉴\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: hrefValue, //요청URL\r\n");
      out.write("                method: \"get\", //요청방식\r\n");
      out.write("                success: function(data){ //data는 응답내용\r\n");
      out.write("                    $(\"section>article\").html(data);\r\n");
      out.write("                }, //성공응답\r\n");
      out.write("                error: function(jqXHR){\r\n");
      out.write("                    alert(\"AJAX요청응답 실패 : 에러코드=\" + jqXHR.status);\r\n");
      out.write("                } //실패응답\r\n");
      out.write("            });\r\n");
      out.write("        break;\r\n");
      out.write("        }\r\n");
      out.write("        return false; \r\n");
      out.write("    });\r\n");
      out.write("            \r\n");
      out.write("              \t\r\n");
      out.write("    //DOM에 장바구니보기의 주문하기버튼 객체가 없어서 click()함수가 효과없음!\r\n");
      out.write("    /* $(\"div.viewcart>button\").click(function(){\r\n");
      out.write("        alert(\"주문하기 버튼 클릭!!!!\");\r\n");
      out.write("    }); */\r\n");
      out.write("\r\n");
      out.write("    //----------이벤트처리 ------------------\r\n");
      out.write("    //DOM에 향후 추가될 자식객체의 이벤트 처리\r\n");
      out.write("    //$(부모객체).on(이벤트종류, 자식객체, 콜백함수)\r\n");
      out.write("\r\n");
      out.write("    //---장바구니보기메뉴의 주문하기버튼 클릭이벤트 START---\r\n");
      out.write("    $(\"section>article\").on('click', 'div.viewcart>button', function(){\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url : './putorder',\r\n");
      out.write("            success: function(responseObj){\r\n");
      out.write("                if(responseObj.status == 1){\r\n");
      out.write("                    alert(\"주문성공!\");\r\n");
      out.write("                    console.log( $(\"header>nav.large>ul>li>a[href='product/list']\"));\r\n");
      out.write("                    $(\"header>nav.large>ul>li>a[href ='product/list']\").trigger(\"click\");\r\n");
      out.write("                    \r\n");
      out.write("                }else if(responseObj.status == 0){\r\n");
      out.write("                    alert(\"로그인부터 하세요\");\r\n");
      out.write("                    console.log( $(\"header>nav.large>ul>li>a[href='./html/login.html']\"));\r\n");
      out.write("                    \r\n");
      out.write("                    $('header>nav.large>ul>li>a[href=\"./html/login.html\"]').trigger(\"click\");\r\n");
      out.write("                }else if(responseObj.status == -1){\r\n");
      out.write("                    alert(\"주문실패: \" + responseObj.msg); \r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(jqXHR){\r\n");
      out.write("                alert(\"오류:\" + jqXHR.status);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        return false;\r\n");
      out.write("    });\r\n");
      out.write("    //---장바구니보기메뉴의 주문하기버튼 클릭이벤트 END---\r\n");
      out.write("            \t\r\n");
      out.write("    //상품목록메뉴 클릭이벤트를 강제 발생\r\n");
      out.write("    $(\"header>nav>ul>li>a[href='product/list']\").trigger(\"click\");\r\n");
      out.write("});\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <!--<h1>스타벅스</h1>-->\r\n");
      out.write("        <h1><a href=\"#\"></a></h1>\r\n");
      out.write("        <nav class=\"large\">\r\n");
      out.write("            <ul>\r\n");
      out.write(" ");

 if(session.getAttribute("loginInfo") == null){ //로그인성공안된 경우
 
      out.write("\r\n");
      out.write("                   <li><a href=\"./html/login.html\">로그인</a></li>\r\n");
      out.write("                    <li><a href=\"./html/signup.html\">가입</a></li>\r\n");

}else{

      out.write("\t\t\t\t\t<li><a href=\"logout\">로그아웃</a></li>\r\n");

}

      out.write("\r\n");
      out.write("                    <li><a href=\"product/list\">상품목록</a></li>\r\n");
      out.write("                    <li><a href=\"viewcart\">장바구니</a></li>\r\n");

 if(session.getAttribute("loginInfo") != null){ //로그인성공된 경우
 
      out.write("\r\n");
      out.write("                    <li><a href=\"vieworder\">주문목록</a></li>\r\n");
} 
      out.write("              \r\n");
      out.write("\t\t\t\t\t<li><a href=\"upload.html\">파일업로드</a>      \r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <nav class=\"small\">\r\n");
      out.write("                <ul>\r\n");
      out.write(" ");

 if(session.getAttribute("loginInfo") == null){
 
      out.write("\r\n");
      out.write("                    <li><a href=\"./html/login.html\">로그인</a></li>\r\n");
      out.write("                    <li><a href=\"./html/signup.html\">가입</a></li>\r\n");

}else{

      out.write("\t\t\t\t\t<li><a href=\"logout\">로그아웃</a></li>\r\n");

}

      out.write("                 \r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("        </header>\r\n");
      out.write("        <section>\r\n");
      out.write("            <article>article...</article>\r\n");
      out.write("            <aside>\r\n");
      out.write("                <div class=\"strawberry\">\r\n");
      out.write("                    <a href=\"https://www.starbucks.co.kr/whats_new/newsView.do?seq=4012\" title=\"자세히 보기\">\r\n");
      out.write("                        <img src=\"https://image.istarbucks.co.kr/upload/common/img/main/2021/strawberrymd_pc_210112.png\" alt=\"\" class=\"pc-badge\">\r\n");
      out.write("                        <img src=\"https://image.istarbucks.co.kr/upload/common/img/main/2021/strawberrymd_mo_210112.png\" alt=\"\" class=\"mobile-badge\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"plcc\">      \r\n");
      out.write("                    <a href=\"/plcc/promotionView.do?eventCode=STH02\" title=\"hyundai card + starbucks\">\r\n");
      out.write("                        <img src=\"https://image.istarbucks.co.kr/upload/common/img/main/2020/plcc_badge_pc.png\" alt=\"\" class=\"pc-badge\">\r\n");
      out.write("                        <img src=\"https://image.istarbucks.co.kr/upload/common/img/main/2020/plcc_badge_mobile.png\" alt=\"\" class=\"mobile-badge\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("        </section>\r\n");
      out.write("        <footer>\r\n");
      out.write("            사업자등록번호 : 201-81-21515 (주)스타벅스커피 코리아 대표이사 : 송 데이비드 호섭 TEL : 1522-3232 개인정보 책임자 : 장석현\r\n");
      out.write("ⓒ 2021 Starbucks Coffee Company. All Rights Reserved.\r\n");
      out.write("        </footer>        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
